# Generated by Django 6.0.1 on 2026-01-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
